language: cpp
os:
    - osx

osx_image:
    #- xcode9.4
    - xcode11.3
    #- xcode12

compiler:
    - clang
    - gcc

env:
    - FLAGS="-DBoost_NO_BOOST_CMAKE=ON"
    - FLAGS="-DUSE_PYTHON_3=ON"

jobs:

    exclude:
        # XCode9.4 has problems with python3
        - osx_image: xcode9.4
          env: FLAGS="-DUSE_PYTHON_3=ON"

    allow_failures:
        - env: FLAGS="-DUSE_PYTHON_3=ON"

    fast_finish: true

addons:
  homebrew:
     update: true
     packages:
      - mesa
      - openal-soft
      - sdl
      - libvorbis
      - jpeg
      - libpng
      - gtk+3
      - gtkglext
      - boost-python
      - boost-python3

script:
  - FLAGS="$FLAGS -DCMAKE_FIND_FRAMEWORK=LAST"
  - ./sh/vsbuild.sh $FLAGS

# CI/CD hookups
# See https://docs.travis-ci.com/user/deployment/releases/
# for what to do for `before_deploy` and `deploy` sections
#before_deploy:
#  - pull the submodule here
#  - ./sh/vspackage.sh
#  - export TRAVIS_TAG="composite tag name here"
#  - git tag ${TRAVIS_TAG}
#deploy:
#    # GitHub Releases
#    provider: releases
#    api_key:
#        secure: "Encrypted GitHub Auth Key" <-- put this in the secrets
#    file:
#       # Upload files in the `packages` directory
#       - packages/*
#    # Ensure the build doesn't get cleaned up so the files are avialable
#    # for the release build
#    skip_clean: true
#    # release is a draft so it can be edited, updated, etc.
#    draft: true
#    # GitHub Releases requires a tag; this guarnatees a tag is set
#    on:
#        tags: true

notifications:
  webhooks:
    if: repo = vegastrike/Vega-Strike-Engine-Source
    urls:
      - https://webhooks.gitter.im/e/1361517953461007f39a  # community room
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
