language: cpp
os:
    - linux

dist: focal # (20.04 LTS)

compiler:
    - gcc

env:
    #- {} # focal's libboost-python-dev no longer supports py2
    - FLAGS='-DUSE_PYTHON_3=ON'

jobs:
    fast_finish: true

addons:
  apt:
    packages:
      - libgl1-mesa-glx
      - freeglut3-dev
      - libopenal-dev
      - libsdl-gfx1.2-dev
      - libvorbis-dev
      - libjpeg-dev
      - libpng-dev
      - libgtk-3-dev
      - libboost-python-dev
      - libboost-log-dev

script:
  - ./sh/vsbuild.sh $FLAGS

# CI/CD hookups
# See https://docs.travis-ci.com/user/deployment/releases/
# for what to do for `before_deploy` and `deploy` sections
#before_deploy:
#  - pull the submodule here
#  - ./sh/vspackage.sh
#  - export TRAVIS_TAG="composite tag name here"
#  - git tag ${TRAVIS_TAG}
#deploy:
#    # GitHub Releases
#    provider: releases
#    api_key:
#        secure: "Encrypted GitHub Auth Key" <-- put this in the secrets
#    file:
#       # Upload files in the `packages` directory
#       - packages/*
#    # Ensure the build doesn't get cleaned up so the files are avialable
#    # for the release build
#    skip_clean: true
#    # release is a draft so it can be edited, updated, etc.
#    draft: true
#    # GitHub Releases requires a tag; this guarnatees a tag is set
#    on:
#        tags: true

notifications:
  webhooks:
    if: repo = vegastrike/Vega-Strike-Engine-Source
    urls:
      - https://webhooks.gitter.im/e/1361517953461007f39a  # community room
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
