name: 'OpenAL/GL detection'

on:
  # Pushes to certain branches,
  push:
    branches: [osx-openal]

jobs:

  compose:
    name: build and cache homebrew
    runs-on: macos-latest

    steps:

      #- name: Clear homebrew cache
      #  run: |
      #    rm -r ~/Library/Caches/Homebrew

      - name: Fetch dependencies from homebrew
        env:
          HOMEBREW_CACHE: '.brew_cache'
        run: |
          brew fetch --deps mesa

      - name: List cache
        run: ls .brew_cache/*_bottle_manifest--*

      #- name: Calculate a hash
      #  id: hash
      #  run: |
      #    hash=`cat ~/Library/Caches/Homebrew/downloads/*bottle_manifest.json | md5sum - | cut -d' ' -f1`
      #    echo ::set-output name=hash::$hash

      - name: Test hash
        run: |
          echo ${{ hashFiles('.brew_cache/downloads/*bottle_manifest.json') }}

      #- name: Create/Access Cache
      #  id: cache
      #  uses: actions/cache@v2
      #  with:
      #    path: ~/Library/Caches/Homebrew
      #    key: ${{ runner.os }}-homebrew_cache-${{ steps.hash.hash }}

