name: 'OpenAL/GL detection'

on:
  # Pushes to certain branches,
  push:
    branches: [osx-openal]

jobs:

  compose:
    name: build and cache homebrew
    runs-on: macos-latest

    steps:

      - name: Create/Access Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-homebrew_cache-2

      - name: List cache
        run: |
          ls -la ~/Library/Caches/Homebrew
          ls -la ~/Library/Caches/Homebrew/downloads

      - name: Clear homebrew cache
        run: |
          rm -r ~/Library/Caches/Homebrew

      - name: Download dependencies from homebrew
        #if: steps.cache.outputs.cache-hit != 'true'
        run: |
          brew fetch --deps mesa

      - name: List cache
        run: ls -la ~/Library/Caches/Homebrew
