name: 'OpenAL/GL detection'

on:
  # Pushes to certain branches,
  push:
    branches: [osx-openal]

jobs:
  build:
    name: find openAL
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        flags:
          - '-DCMAKE_FIND_FRAMEWORK=LAST'
          - '-DCMAKE_FIND_FRAMEWORK=NEVER'

    steps:

    #- name: Install OpenAL from homebrew
    #  if: always()
    #  run: brew install openal-soft

    #- name: Install mesa from homebrew
    #  if: always()
    #  run: brew install mesa

    - name: Install glut from homebrew
      if: always()
      run: brew install freeglut

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: false

    #- name: Link mesa (includes)
    #  run: ln -s /usr/local/include/GL /usr/local/include/OpenGL

    #- name: Link mesa (libs)
    #  run: ln -s /usr/local/lib/libGL.dylib /usr/local/lib/libOpenGL.dylib

    - name: Find with CMake
      if: always()
      env:
        FLAGS:      ${{ matrix.flags }}
      run: find/script.sh $FLAGS
