name: 'OpenAL/GL detection'

on:
  # Pushes to certain branches,
  push:
    branches: [osx-openal]

jobs:
  build:
    name: find openAL
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        flags: ['-DCMAKE_FIND_FRAMEWORK=LAST']

    steps:

    #- run: ls /usr/lib/lib*
    #  if: always()

    #- run: ls /usr/local/lib/lib*
    #  if: always()

    #- run: ls /usr/local/opt/lib*
    #  if: always()

    #- name: Install mesa
    #  if: always()
    #  run: brew install mesa openal-soft

    #- run: ls /usr/lib/lib*
    #  if: always()

    #- run: ls /usr/local/lib/lib*
    #  if: always()

    #- run: ls /usr/local/opt/lib*
    #  if: always()

    - run: echo $PATH
      if: always()

    - env:
        PATH: "/usr/local/opt/openal-soft/bin:$PATH"
      run: echo $PATH
      if: always()

    - run: pwd
      if: always()

    - run: ls .
      if: always()

    - name: Find with CMake
      if: always()
      env:
        FLAGS:      ${{ matrix.flags }}
      run: find/script $FLAGS

    - name: Find with CMake (alt)
      if: always()
      env:
        FLAGS:      ${{ matrix.flags }}
      run: script/script $FLAGS
